### ISSUE TITLE
Connect XMTP network error

### ISSUE THREAD

**Issue by Top-Kraken** [xmtp/example-chat-react#59] opened 2022-05-28 19:36 UTC
Hi, I'm working on Shanghai Hackathon and tried to run this chat on my end.
I use MetaMask and Ropsten testnet and connecting wallets works well.
But once I input the account address of another one, it shows
"Recipient is not on the XMTP network" error.
I also try to use https://xmtp.netlify.app/ but it also shows above message.
How can I resolve this? I'm using Google Chrome.

![image](https://user-images.githubusercontent.com/86540499/170840384-d21ec70f-d358-4f3c-a497-4954f6195d61.png)
![image](https://user-images.githubusercontent.com/86540499/170840395-8a4dc342-cc7c-42e9-9575-605f5cda45a3.png)

As you can see, these 2 accounts are connected to the website.

**Comment by saulmc** [comment] 2022-05-28 23:35
Hi @Top-Kraken, could you please try again? We were able to reproduce this issue in playnet and just pushed a fix.

**Comment by galligan** [comment] 2022-05-29 10:53
@Top-Kraken this appears to be the same issue as #58. We have since resolved the underlying issue in our testnet and things should work as expected now.

**Closed** 2022-05-29 10:53 UTC
Labels: bug, duplicate
